# Generated by Django 4.2.1 on 2023-06-04 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Records',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_Schedule',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_appointment', models.DateField()),
                ('current_appointment_schedule', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('procedure', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Done', 'done'), ('Missed', 'missed')], max_length=30)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_records')),
            ],
        ),
    ]
