# Generated by Django 4.2.1 on 2023-06-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_patient_records_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_records',
            name='sex',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='male', max_length=10),
            preserve_default=False,
        ),
    ]
