# Generated by Django 4.2.1 on 2023-06-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_patient_records_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_schedule',
            name='last_appointment',
            field=models.DateField(default=None, null=True),
        ),
    ]
