# Generated by Django 4.2.1 on 2023-06-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_appointment_schedule_last_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_schedule',
            name='appointment_id',
            field=models.BigAutoField(choices=[], primary_key=True, serialize=False),
        ),
    ]
