# Generated by Django 4.2.1 on 2023-06-11 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_appointment_schedule_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_schedule',
            name='appointment_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment_schedule',
            name='patient_id',
            field=models.ForeignKey(choices=[], on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_records'),
        ),
    ]
