# Generated by Django 4.2.1 on 2023-06-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_appointment_schedule_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_schedule',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_records'),
        ),
    ]
