# Generated by Django 4.2.1 on 2023-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_appointment_schedule_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_records',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
    ]
