# Generated by Django 4.2.1 on 2023-06-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0015_delete_appointment_schedule_delete_patient_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Records',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=3)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('contact_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_Schedule',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_appointment_schedule', models.DateField()),
                ('last_appointment', models.DateField(default=None, null=True)),
                ('appointment_time', models.TimeField()),
                ('procedure', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Missed', 'Missed')], max_length=15)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_records')),
            ],
        ),
    ]
